version: '3'

volumes:
  postgres-data:
    driver: local
  mongo-data:
    driver: local
  zookeeper-data:
    driver: local
  kafka-data:
    driver: local
  redis-data:
    driver: local

services:
  postgres-hotel-booking:
    image: postgres:15.2
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1212
      POSTGRES_DB: hotel-booking
    ports:
      - "10001:10001"
    command: -p 10001

  mongodb:
    image: mongo:4.4.19
    container_name: mongodb
    volumes:
      - mongo-data:/data
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: 1212

  mongo-express:
    image: mongo-express:0.54.0
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1212
      ME_CONFIG_MONGODB_SERVER: mongodb

#  postgres-hotel-booking:
#    image: bitnami/postgresql:15.2.0
#    volumes:
#      - postgres-data-hotel-booking:/bitnami/postgresql
#    environment:
#      POSTGRESQL_USERNAME: postgres
#      POSTGRESQL_PASSWORD: 1212
#      POSTGRESQL_DATABASE: hotel-booking
#      POSTGRESQL_PORT_NUMBER: 10001
#    ports:
#      - "10001:10001"

  zookeeper:
    image: bitnami/zookeeper:3.7.1
    volumes:
      - "zookeeper-data:/bitnami/zookeeper"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.4.0
    volumes:
      - "kafka-data:/bitnami/kafka"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  redis:
    image: bitnami/redis:7.0.9
    volumes:
      - "redis-data:/bitnami/redis/data"
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "6379:6379"